name: "rsync"
description: "rsync files to a remote server"
inputs:
  path:
    description: "The path to the files to be rsynced"
    required: false
    default: ${{ github.workspace }}/
  flags:
    description: "The flags to be used with rsync"
    required: false
    default: "-avz --no-o --no-g --delete"
  excludes:
    description: "The files and directories to be excluded"
    required: false
  ssh-config:
    description: "The SSH config to be used"
    required: true
  ssh-path:
    description: "The path on the remote server to be used"
    required: true
runs:
  using: "composite"
  steps:
    - name: Convert excludes to rsync format
      id: convert-excludes
      run: |
        echo $INPUT
        EXCLUDES=""
        if [ -n "$INPUT" ]; then
          EXCLUDES=$(echo $INPUT | sed '/./s/^/--exclude /' | tr '\n' ' ')
        fi
        echo "excludes=$EXCLUDES" >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        INPUT: ${{ inputs.excludes }}
    - name: rsync
      run: |
        rsync $FLAGS $EXCLUDES $LOCAL_PATH $SSH_CONFIG:$SSH_PATH
      shell: bash
      env:
        LOCAL_PATH: ${{ inputs.path }}
        FLAGS: ${{ inputs.flags }}
        EXCLUDES: ${{ steps.convert-excludes.outputs.excludes }}
        SSH_CONFIG: ${{ inputs.ssh-config }}
        SSH_PATH: ${{ inputs.ssh-path }}
