name: "Configure SSH"
description: "Configures SSH with supplied credentials"
inputs:
  environment:
    description: "The environment to configure SSH for"
    required: false
    default: "production"
  ssh-host:
    description: "The SSH host to be used"
    required: true
  ssh-user:
    description: "The SSH user to be used"
    required: true
  ssh-key:
    description: "The SSH key to be used"
    required: true
outputs:
  ssh-config:
    description: "The SSH configuration"
    value: ${{ inputs.environment }}
runs:
  using: "composite"
  steps:
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/$ENVIRONMENT.key
        chmod 600 ~/.ssh/$ENVIRONMENT.key
        cat >>~/.ssh/config <<END
        Host $ENVIRONMENT
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/$ENVIRONMENT.key
          StrictHostKeyChecking no
        END
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        SSH_HOST: ${{ inputs.ssh-host }}
        SSH_USER: ${{ inputs.ssh-user }}
        SSH_KEY: ${{ inputs.ssh-key }}
